export const httpStatusCodes: { [key: number]: string } = {
  100: 'Continue - The server has received the request headers and the client should proceed to send the request body.',
  101: 'Switching Protocols - The server is switching protocols because the client requested the switch.',
  102: 'Processing - The server has received and is processing the request, but no response is available yet.',
  103: 'Early Hints - Used to return some response headers before final HTTP message.',
  200: 'OK - The request has succeeded.',
  201: 'Created - The request has succeeded and a new resource has been created.',
  202: 'Accepted - The request has been accepted for processing, but the processing has not been completed.',
  203: "Non-Authoritative Information - The request was successful but the enclosed payload has been modified from the origin server's response by a transforming proxy.",
  204: 'No Content - The request has succeeded but there is no content to return.',
  205: 'Reset Content - The server has fulfilled the request and desires that the client reset the document view which caused the request to be sent.',
  206: 'Partial Content - The server is delivering only part of the resource due to a range header sent by the client.',
  207: 'Multi-Status - The message body that follows is an XML message and can contain a number of separate response codes, depending on how many sub-requests were made.',
  208: 'Already Reported - The members of a DAV binding have already been enumerated in a previous reply to this request, and are not being included again.',
  226: 'IM Used - The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.',
  300: 'Multiple Choices - The request has more than one possible response.',
  301: 'Moved Permanently - The requested resource has been assigned a new permanent URI and any future references to this resource should use one of the returned URIs.',
  302: 'Found - The requested resource resides temporarily under a different URI.',
  303: 'See Other - The response to the request can be found under another URI using a GET method.',
  304: 'Not Modified - The client has performed a conditional GET request and access is allowed, but the document has not been modified.',
  305: 'Use Proxy - The requested resource is only available through a proxy, and the address for the proxy is specified in the response.',
  306: 'Switch Proxy - No longer used. The requested resource is only available through a proxy, and the address for the proxy is specified in the response.',
  307: 'Temporary Redirect - The requested resource resides temporarily under a different URI.',
  308: 'Permanent Redirect - The requested resource has been assigned a new permanent URI and any future references to this resource should use one of the returned URIs.',
  400: 'Bad Request - The server cannot or will not process the request due to an apparent client error.',
  401: 'Unauthorized - Authentication is required and has failed or has not yet been provided.',
  402: 'Payment Required - Reserved for future use.',
  403: 'Forbidden - The client does not have access rights to the content.',
  404: 'Not Found - The server can not find the requested resource.',
  405: 'Method Not Allowed - A request method is not supported for the requested resource.',
  406: 'Not Acceptable - The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.',
  407: 'Proxy Authentication Required - The client must first authenticate itself with the proxy.',
  408: 'Request Timeout - The server timed out waiting for the request.',
  409: 'Conflict - The request could not be completed due to a conflict with the current state of the target resource.',
  410: 'Gone - The requested resource is no longer available at the server and no forwarding address is known.',
  411: 'Length Required - The request did not specify the length of its content, which is required by the requested resource.',
  412: 'Precondition Failed - One or more preconditions given in the request header fields evaluated to false when tested on the server.',
  413: 'Payload Too Large - The server is refusing to process a request because the request payload is larger than the server is willing or able to process.',
  414: 'URI Too Long - The server is refusing to service the request because the request-target is longer than the server is willing to interpret.',
  415: 'Unsupported Media Type - The origin server is refusing to service the request because the payload is in a format not supported by this method on the target resource.',
  416: 'Range Not Satisfiable - The requested range is not satisfiable by the target resource.',
  417: 'Expectation Failed - The expectation given in an Expect request-header field could not be met by this server.',
  418: "I'm a teapot - The server refuses to brew coffee because it is, in fact, a teapot.",
  421: 'Misdirected Request - The request was directed at a server that is not able to produce a response.',
  422: 'Unprocessable Entity - The request was well-formed but was unable to be followed due to semantic errors.',
  423: 'Locked - The resource that is being accessed is locked.',
  424: 'Failed Dependency - The request failed due to failure of a previous request.',
  425: 'Too Early - Indicates that the server is unwilling to risk processing a request that might be replayed.',
  426: 'Upgrade Required - The server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol.',
  428: 'Precondition Required - The server requires the request to be conditional.',
  429: 'Too Many Requests - The user has sent too many requests in a given amount of time.',
  431: 'Request Header Fields Too Large - The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.',
  451: 'Unavailable For Legal Reasons - The server is denying access to the resource in response to a legal demand.',
  500: "Internal Server Error - The server has encountered a situation it doesn't know how to handle.",
  501: 'Not Implemented - The server does not support the functionality required to fulfill the request.',
  502: 'Bad Gateway - The server, while acting as a gateway or proxy, received an invalid response from the upstream server.',
  503: 'Service Unavailable - The server is currently unavailable (overloaded or down).',
  504: 'Gateway Timeout - The server, acting as a gateway or proxy, did not receive a timely response from the upstream server.',
  505: 'HTTP Version Not Supported - The server does not support the HTTP protocol version that was used in the request.',
  506: 'Variant Also Negotiates - The server has an internal configuration error: transparent content negotiation for the request results in a circular reference.',
  507: 'Insufficient Storage - The server is unable to store the representation needed to complete the request.',
  508: 'Loop Detected - The server detected an infinite loop while processing a request.',
  510: 'Not Extended - Further extensions to the request are required for the server to fulfill it.',
  511: 'Network Authentication Required - The client needs to authenticate to gain network access.',
};
